server:
  port: 7001
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
eureka:
  instance:
    hostname: eureka7001.com    #eureka服务端的实例名字  这里一开始是localhost 但是在本地配置了集群eureka7001.com映射到localhost
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
  server:
    #eureka中的自我保护机制
    enable-self-preservation: false
